version: '2'
services:
    bpmprojectsupport-app:
        image: bpmprojectsupport
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://bpmprojectsupport-mysql:3306/bpmprojectsupport?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    bpmprojectsupport-mysql:
        extends:
            file: mysql.yml
            service: bpmprojectsupport-mysql
